#!/bin/bash
echo "🚀 Démarrage de FinCredit Pro..."
echo ""
echo "Terminal 1 - Backend:"
echo "  cd backend && npm run dev"
echo ""
echo "Terminal 2 - Frontend:"
echo "  cd frontend && ng serve"
echo ""
echo "🌐 Frontend : http://localhost:4200"
echo "🔌 API      : http://localhost:3000"
echo ""
echo "Comptes:"
echo "  Admin  : admin@fincredit.tn / admin123"
echo "  Client : client@test.tn    / client123"
